"use client";
/* eslint-disable @next/next/no-img-element */
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Project={id:string;title:string;topic:string;format:string;quantity:string;mode:string;status:string;currentStep:string;readyForAi:boolean;ideaText:string;scriptText:string;promptsText:string;createdAt:string;updatedAt:string};
type Scene={id:string;projectId:string;position:number;title:string;narration:string;prompt:string;variant:string;status:string;imageUrl:string;imageFile:string;notes:string;createdAt:string;updatedAt:string};
type Job={id:string;projectId:string;sceneId:string;type:string;status:string;prompt:string;outputUrl:string;outputFile:string;error:string;attempt:number;createdAt:string;updatedAt:string};
type FullProject=Project&{scenes:Scene[];jobs:Job[];summary:{sceneCount:number;imageCount:number;jobCount:number;pendingJobs:number}};
type Tab="overview"|"idea"|"script"|"scenes"|"prompts"|"images"|"production";
const tabs:[Tab,string,string][]=[["overview","VISÃO","⌂"],["idea","IDEIA","✦"],["script","ROTEIRO","≡"],["scenes","CENAS","▦"],["prompts","PROMPTS","›_"],["images","IMAGENS","◫"],["production","PRODUÇÃO","▶"]];

export default function Page(){
 const[projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(""),[project,setProject]=useState<FullProject|null>(null),[tab,setTab]=useState<Tab>("overview"),[sync,setSync]=useState<"loading"|"ok"|"locked"|"error">("loading"),[newOpen,setNewOpen]=useState(false),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[mcpEnabled,setMcpEnabled]=useState(false),[mcpKeySaved,setMcpKeySaved]=useState(false);
 const headers=useCallback(()=>{if(typeof window==="undefined")return{"content-type":"application/json"};const enabled=localStorage.getItem("corvo_mcp_enabled")==="1";const token=localStorage.getItem("corvo_mcp_key")?.trim()||"";return{"content-type":"application/json",...(enabled&&token?{authorization:`Bearer ${token}`}:{})}},[]);
 const loadProjects=useCallback(async(preferId?:string)=>{try{setSync("loading");const r=await fetch("/api/projects?limit=100",{headers:headers()});if(r.status===401){setSync("locked");return}if(!r.ok)throw new Error();const d=await r.json() as {projects:Project[]};setProjects(d.projects);setSync("ok");const target=preferId||selected||d.projects[0]?.id||"";if(target){setSelected(target);const pr=await fetch(`/api/projects?id=${encodeURIComponent(target)}`,{headers:headers()});if(pr.ok){const pd=await pr.json() as {project:FullProject};setProject(pd.project)}}else setProject(null)}catch{setSync("error")}},[headers,selected]);
 const loadProject=useCallback(async(id:string)=>{if(!id)return;try{const r=await fetch(`/api/projects?id=${encodeURIComponent(id)}`,{headers:headers()});if(r.status===401){setSync("locked");return}if(!r.ok)throw new Error();const d=await r.json() as {project:FullProject};setProject(d.project);setProjects(p=>p.map(x=>x.id===id?d.project:x));setSync("ok")}catch{setSync("error")}},[headers]);
 useEffect(()=>{const key=localStorage.getItem("corvo_mcp_key")?.trim()||"";const stored=localStorage.getItem("corvo_mcp_enabled");const enabled=!!key&&(stored===null||stored==="1");setMcpKeySaved(!!key);setMcpEnabled(enabled);if(key&&stored===null)localStorage.setItem("corvo_mcp_enabled","1");void loadProjects()},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(!selected)return;const id=setInterval(()=>{if(project?.readyForAi||project?.summary.pendingJobs)void loadProject(selected)},7000);return()=>clearInterval(id)},[selected,project?.readyForAi,project?.summary.pendingJobs,loadProject]);
 function toast(s:string){setNotice(s);setTimeout(()=>setNotice(""),2600)}
 async function toggleMcp(){const current=localStorage.getItem("corvo_mcp_key")?.trim()||"";const enabled=localStorage.getItem("corvo_mcp_enabled")==="1";if(enabled){localStorage.setItem("corvo_mcp_enabled","0");setMcpEnabled(false);setSync("locked");toast("MCP desligado — chave preservada");return}let key=current;if(!key){const entered=prompt("Cole a chave MCP configurada em App_key_corvoapp na Vercel:","");if(!entered?.trim())return;key=entered.trim();localStorage.setItem("corvo_mcp_key",key);setMcpKeySaved(true)}setSync("loading");try{const check=await fetch("/api/auth-check",{headers:{authorization:`Bearer ${key}`}});const data=await check.json().catch(()=>({})) as {code?:string;message?:string};if(!check.ok){localStorage.setItem("corvo_mcp_enabled","0");setMcpEnabled(false);setSync(check.status===401?"locked":"error");if(data.code==="MCP_KEY_NOT_CONFIGURED")toast("Vercel ainda não carregou App_key_corvoapp — faça novo deploy");else if(data.code==="MCP_KEY_INVALID")toast("Chave diferente da App_key_corvoapp do deploy");else toast(data.message||"Falha ao validar o MCP");return}localStorage.setItem("corvo_mcp_enabled","1");setMcpEnabled(true);await loadProjects();toast("MCP ligado · chave e banco validados")}catch{localStorage.setItem("corvo_mcp_enabled","0");setMcpEnabled(false);setSync("error");toast("Não foi possível alcançar o diagnóstico do MCP")}}
 function changeMcpKey(){const current=localStorage.getItem("corvo_mcp_key")||"";const entered=prompt("Alterar chave MCP salva neste navegador:",current);if(entered===null)return;const key=entered.trim();if(!key){localStorage.removeItem("corvo_mcp_key");localStorage.setItem("corvo_mcp_enabled","0");setMcpKeySaved(false);setMcpEnabled(false);setSync("locked");toast("Chave removida");return}localStorage.setItem("corvo_mcp_key",key);setMcpKeySaved(true);toast("Chave salva") }
 async function createProject(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={title:String(f.get("title")||"").trim(),topic:String(f.get("topic")||"").trim(),format:String(f.get("format")||"REELS"),quantity:String(f.get("quantity")||"1 VÍDEO"),mode:String(f.get("mode")||"RÁPIDO")};if(!body.title)return;setBusy(true);const r=await fetch("/api/projects",{method:"POST",headers:headers(),body:JSON.stringify(body)});setBusy(false);if(!r.ok){toast("Não foi possível criar");return}const d=await r.json() as {project:Project};setNewOpen(false);setTab("overview");await loadProjects(d.project.id);toast("Projeto criado")}
 async function patchProject(changes:Partial<Project>,message="Projeto salvo"){if(!project)return;setBusy(true);const r=await fetch("/api/projects",{method:"PATCH",headers:headers(),body:JSON.stringify({id:project.id,changes})});setBusy(false);if(r.ok){await loadProject(project.id);toast(message)}else toast("Falha ao salvar")}
 async function action(action:"start"|"pause"){if(!project)return;setBusy(true);const r=await fetch("/api/projects",{method:"PATCH",headers:headers(),body:JSON.stringify({id:project.id,action})});setBusy(false);if(r.ok){await loadProject(project.id);toast(action==="start"?"Projeto liberado para o ChatGPT":"Projeto pausado")}}
 async function removeProject(){if(!project||!confirm(`Excluir “${project.title}” e todos os dados?`))return;await fetch(`/api/projects?id=${encodeURIComponent(project.id)}`,{method:"DELETE",headers:headers()});setProject(null);setSelected("");await loadProjects();toast("Projeto excluído")}
 async function saveScene(scene:Scene){const r=await fetch("/api/scenes",{method:"PATCH",headers:headers(),body:JSON.stringify(scene)});if(r.ok){await loadProject(scene.projectId);toast(`Cena ${scene.position} salva`)}}
 async function addScene(){if(!project)return;const pos=(project.scenes.at(-1)?.position||0)+1;const r=await fetch("/api/scenes",{method:"POST",headers:headers(),body:JSON.stringify({scene:{projectId:project.id,position:pos,title:`Cena ${String(pos).padStart(2,"0")}`,narration:"",prompt:"",variant:"SINGLE",status:"PENDING"}})});if(r.ok){await loadProject(project.id);toast("Cena adicionada")}}
 async function deleteScene(id:string){if(!project)return;await fetch(`/api/scenes?id=${encodeURIComponent(id)}&projectId=${encodeURIComponent(project.id)}`,{method:"DELETE",headers:headers()});await loadProject(project.id);toast("Cena removida")}
 async function createJobs(){if(!project)return;const scenes=project.scenes.filter(s=>s.prompt.trim()&&!project.jobs.some(j=>j.sceneId===s.id&&!["FAILED","CANCELLED"].includes(j.status)));if(!scenes.length){toast("Nenhum prompt novo para enviar");return}const jobs=scenes.map(s=>({projectId:project.id,sceneId:s.id,type:"GENERATE_IMAGE",status:"PENDING",prompt:s.prompt,outputFile:`${project.id}_${String(s.position).padStart(2,"0")}.png`}));const r=await fetch("/api/jobs",{method:"POST",headers:headers(),body:JSON.stringify({jobs})});if(r.ok){await loadProject(project.id);setTab("production");toast(`${jobs.length} job(s) criado(s)`)}}
 function backup(){if(!project)return;const blob=new Blob([JSON.stringify(project,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${project.id}_backup.json`;a.click();URL.revokeObjectURL(a.href)}
 const progress=useMemo(()=>{if(!project)return 0;let n=0;if(project.ideaText)n++;if(project.scriptText)n++;if(project.scenes.length)n++;if(project.scenes.some(s=>s.prompt))n++;if(project.scenes.length&&project.scenes.every(s=>s.imageUrl))n++;return Math.round(n/5*100)},[project]);
 return <main className="shell">
  <aside className="side"><div className="brand"><div className="mark">C</div><div><strong>CORVO</strong><small>ROTEIRO · CORE</small></div></div><button className="newProject" onClick={()=>setNewOpen(true)}>＋ NOVO PROJETO</button><div className="projectLabel">PROJETOS</div><div className="projectList">{projects.map(p=><button key={p.id} className={selected===p.id?"active":""} onClick={()=>{setSelected(p.id);setTab("overview");void loadProject(p.id)}}><span className={`dot ${p.readyForAi?"ready":""}`}/><div><b>{p.title}</b><small>{p.format} · {p.currentStep}</small></div></button>)}{!projects.length&&sync==="ok"&&<p className="emptySide">Nenhum projeto ainda.</p>}</div><div className="sideBottom"><button className={`connection ${mcpEnabled?sync:"locked"}`} onClick={toggleMcp}><span>●</span><div><b>{mcpEnabled?(sync==="ok"?"MCP LIGADO":sync==="loading"?"CONECTANDO":"MCP LIGADO · ERRO"):"MCP DESLIGADO"}</b><small>{mcpKeySaved?(mcpEnabled?"clique para desligar":"chave salva · clique para ligar"):"clique para cadastrar a chave"}</small></div></button>{mcpKeySaved&&<button className="keyEdit" onClick={changeMcpKey}>ALTERAR CHAVE SALVA</button>}</div></aside>
  <section className="workspace"><header className="top"><div><span className="crumb">CORVO / ROTEIRO</span>{project&&<b>{project.id}</b>}</div><div className="topActions">{project&&<><button onClick={backup}>↓ BACKUP</button><button className={project.readyForAi?"pause":"start"} disabled={busy} onClick={()=>void action(project.readyForAi?"pause":"start")}>{project.readyForAi?"Ⅱ PAUSAR":"▶ INICIAR"}</button></>}<i>LO</i></div></header>
  {!project?<Welcome locked={sync==="locked"} connect={toggleMcp} create={()=>setNewOpen(true)}/>:<div className="projectPage">
    <section className="hero"><div><div className="eyebrow"><span className={project.readyForAi?"live":""}>● {project.readyForAi?"LIBERADO PARA CHATGPT":project.status}</span><em>{project.format}</em><em>{project.mode}</em></div><input className="heroTitle" value={project.title} onChange={e=>setProject({...project,title:e.target.value})} onBlur={()=>void patchProject({title:project.title},"Título salvo")}/><input className="heroTopic" value={project.topic} placeholder="Tema do projeto" onChange={e=>setProject({...project,topic:e.target.value})} onBlur={()=>void patchProject({topic:project.topic},"Tema salvo")}/></div><div className="progressRing"><b>{progress}%</b><small>ESTRUTURA</small></div></section>
    <nav className="tabs">{tabs.map(t=><button key={t[0]} className={tab===t[0]?"active":""} onClick={()=>setTab(t[0])}><span>{t[2]}</span>{t[1]}{t[0]==="scenes"&&project.scenes.length>0?<i>{project.scenes.length}</i>:null}{t[0]==="images"&&project.summary.imageCount>0?<i>{project.summary.imageCount}</i>:null}{t[0]==="production"&&project.summary.pendingJobs>0?<i>{project.summary.pendingJobs}</i>:null}</button>)}</nav>
    {tab==="overview"&&<Overview project={project} progress={progress} go={setTab} start={()=>void action("start")}/>} 
    {tab==="idea"&&<Editor title="IDEIA" subtitle="A premissa e direção central do vídeo." value={project.ideaText} placeholder="A ideia será escrita aqui pelo ChatGPT ou por você..." save={v=>patchProject({ideaText:v,currentStep:v?"ROTEIRO":"IDEIA",status:v?"IN_PROGRESS":"DRAFT"},"Ideia salva")}/>} 
    {tab==="script"&&<Editor title="ROTEIRO" subtitle="Texto final que orienta cenas, narração e ritmo." value={project.scriptText} placeholder="Cole ou escreva o roteiro..." save={v=>patchProject({scriptText:v,currentStep:v?"CENAS":"ROTEIRO",status:"IN_PROGRESS"},"Roteiro salvo")}/>} 
    {tab==="scenes"&&<ScenesView scenes={project.scenes} add={addScene} save={saveScene} remove={deleteScene}/>} 
    {tab==="prompts"&&<PromptsView project={project} saveScene={saveScene} saveMaster={v=>patchProject({promptsText:v,currentStep:"IMAGENS",status:"IN_PROGRESS"},"Prompts salvos")}/>} 
    {tab==="images"&&<ImagesView project={project}/>} 
    {tab==="production"&&<Production project={project} createJobs={createJobs} refresh={()=>loadProject(project.id)}/>} 
    <footer className="projectFooter"><button className="danger" onClick={removeProject}>EXCLUIR PROJETO</button><span>Última alteração {new Date(project.updatedAt).toLocaleString("pt-BR")}</span></footer>
  </div>}</section>
  {newOpen&&<NewProject close={()=>setNewOpen(false)} submit={createProject} busy={busy}/>} {notice&&<div className="toast">✓ {notice}</div>}
 </main>
}

function Welcome({locked,connect,create}:{locked:boolean;connect:()=>void;create:()=>void}){return <div className="welcome"><div className="raven">C</div><span>NOVO CORVO</span><h1>Roteiro com menos<br/>infraestrutura.</h1><p>Um único Core persistente, ChatGPT via MCP e jobs prontos para o Flow Agent.</p><div><button className="primary" onClick={create}>＋ CRIAR PRIMEIRO PROJETO</button>{locked&&<button onClick={connect}>CONECTAR AO CORE</button>}</div><section><article><b>01</b><strong>CORE ÚNICO</strong><small>D1 mantém projeto, roteiro, cenas e jobs.</small></article><article><b>02</b><strong>CHATGPT + MCP</strong><small>Sem Bridge e sem vários GPTs físicos.</small></article><article><b>03</b><strong>AGENT EXECUTOR</strong><small>Flow fica isolado como braço de produção.</small></article></section></div>}
function Overview({project,progress,go,start}:{project:FullProject;progress:number;go:(t:Tab)=>void;start:()=>void}){const cards:[[Tab,string,string,boolean],...Array<[Tab,string,string,boolean]>]=[["idea","IDEIA","Premissa e direção do vídeo",!!project.ideaText],["script","ROTEIRO","Texto principal e narrativa",!!project.scriptText],["scenes","CENAS",`${project.scenes.length} cenas estruturadas`,project.scenes.length>0],["prompts","PROMPTS","Prompts visuais por cena",project.scenes.some(s=>s.prompt)],["images","IMAGENS",`${project.summary.imageCount}/${project.scenes.length||0} resultados`,project.summary.imageCount>0],["production","PRODUÇÃO",`${project.summary.pendingJobs} jobs pendentes`,project.summary.jobCount>0]];return <div className="contentGrid"><section className="panel mainPanel"><div className="panelHead"><div><em>FLUXO DO PROJETO</em><h2>Uma fonte de verdade</h2></div><b>{progress}%</b></div><div className="flowCards">{cards.map(([t,label,desc,done],i)=><button key={t} onClick={()=>go(t)} className={done?"done":""}><i>{String(i+1).padStart(2,"0")}</i><span><b>{label}</b><small>{desc}</small></span><em>{done?"✓":"→"}</em></button>)}</div></section><section className="panel statePanel"><em>ESTADO DO CORE</em><h2>{project.readyForAi?"Pronto para o ChatGPT":"Aguardando comando"}</h2><div className="stateLine"><span>ETAPA ATUAL</span><b>{project.currentStep}</b></div><div className="stateLine"><span>STATUS</span><b>{project.status}</b></div><div className="stateLine"><span>JOBS</span><b>{project.summary.jobCount}</b></div><div className="stateLine"><span>IMAGENS</span><b>{project.summary.imageCount}</b></div><p>{project.readyForAi?"Ao consultar obter_contexto_corvo, o ChatGPT encontrará este projeto como liberado e poderá continuar do estado atual.":"O botão Iniciar apenas marca este projeto como READY no Core. Nenhuma API OpenAI é chamada."}</p>{!project.readyForAi&&<button className="primary wide" onClick={start}>▶ LIBERAR PROJETO</button>}</section></div>}
function Editor({title,subtitle,value,placeholder,save}:{title:string;subtitle:string;value:string;placeholder:string;save:(v:string)=>void}){const[v,setV]=useState(value);useEffect(()=>setV(value),[value]);return <section className="editorPanel"><header><div><em>ARTEFATO</em><h2>{title}</h2><p>{subtitle}</p></div><span>{v.length.toLocaleString("pt-BR")} caracteres</span></header><textarea value={v} onChange={e=>setV(e.target.value)} placeholder={placeholder}/><footer><small>O ChatGPT também pode editar este conteúdo diretamente pelo MCP.</small><button className="primary" onClick={()=>save(v)}>✓ SALVAR {title}</button></footer></section>}
function ScenesView({scenes,add,save,remove}:{scenes:Scene[];add:()=>void;save:(s:Scene)=>void;remove:(id:string)=>void}){return <section className="stack"><div className="sectionTitle"><div><em>ESTRUTURA VISUAL</em><h2>Cenas</h2><p>Cada cena é um objeto independente e pode receber prompt, imagem e job.</p></div><button className="primary" onClick={add}>＋ ADICIONAR CENA</button></div>{!scenes.length?<Empty title="Nenhuma cena" text="Crie manualmente ou peça ao ChatGPT para transformar o roteiro em cenas."/>:<div className="sceneList">{scenes.map(s=><SceneCard key={s.id} scene={s} save={save} remove={remove}/>)}</div>}</section>}
function SceneCard({scene,save,remove}:{scene:Scene;save:(s:Scene)=>void;remove:(id:string)=>void}){const[s,setS]=useState(scene);useEffect(()=>setS(scene),[scene]);return <article className="sceneCard"><header><b>{String(s.position).padStart(2,"0")}</b><input value={s.title} onChange={e=>setS({...s,title:e.target.value})}/><select value={s.variant} onChange={e=>setS({...s,variant:e.target.value})}><option>SINGLE</option><option>A</option><option>B</option></select><span className={`sceneStatus ${s.status.toLowerCase()}`}>{s.status}</span></header><label>NARRAÇÃO<textarea rows={3} value={s.narration} onChange={e=>setS({...s,narration:e.target.value})}/></label><label>PROMPT VISUAL<textarea rows={4} value={s.prompt} onChange={e=>setS({...s,prompt:e.target.value})}/></label><footer><button className="textDanger" onClick={()=>remove(s.id)}>REMOVER</button><button onClick={()=>save(s)}>✓ SALVAR CENA</button></footer></article>}
function PromptsView({project,saveScene,saveMaster}:{project:FullProject;saveScene:(s:Scene)=>void;saveMaster:(v:string)=>void}){const[master,setMaster]=useState(project.promptsText);useEffect(()=>setMaster(project.promptsText),[project.promptsText]);return <section className="stack"><div className="sectionTitle"><div><em>GERAÇÃO</em><h2>Prompts</h2><p>O campo consolidado é opcional; os prompts executáveis vivem em cada cena.</p></div></div><div className="promptGrid"><section className="editorMini"><header><b>PROMPTS CONSOLIDADOS</b><button onClick={()=>saveMaster(master)}>SALVAR</button></header><textarea value={master} onChange={e=>setMaster(e.target.value)} placeholder="01|prompt...\n02|prompt..."/></section><section className="promptScenes">{project.scenes.map(s=><PromptRow key={s.id} scene={s} save={saveScene}/>)}</section></div></section>}
function PromptRow({scene,save}:{scene:Scene;save:(s:Scene)=>void}){const[v,setV]=useState(scene.prompt);useEffect(()=>setV(scene.prompt),[scene.prompt]);return <article><b>{String(scene.position).padStart(2,"0")}</b><textarea value={v} onChange={e=>setV(e.target.value)} placeholder="Prompt visual da cena"/><button onClick={()=>save({...scene,prompt:v})}>✓</button></article>}
function ImagesView({project}:{project:FullProject}){const withImages=project.scenes.filter(s=>s.imageUrl);return <section className="stack"><div className="sectionTitle"><div><em>RESULTADOS</em><h2>Galeria</h2><p>{withImages.length} imagens vinculadas ao Core.</p></div></div>{!withImages.length?<Empty title="Nenhuma imagem ainda" text="Quando o Agent concluir um job, o resultado será vinculado automaticamente à cena."/>:<div className="gallery">{withImages.map(s=><article key={s.id}><div><img src={s.imageUrl} alt={s.title}/><span>{String(s.position).padStart(2,"0")}</span></div><b>{s.title}</b><small>{s.imageFile||s.imageUrl}</small></article>)}</div>}</section>}
function Production({project,createJobs,refresh}:{project:FullProject;createJobs:()=>void;refresh:()=>void}){return <section className="stack"><div className="sectionTitle"><div><em>FILA ÚNICA</em><h2>Produção</h2><p>Jobs são contratos simples para o Corvo Agent executar; o app não conhece detalhes internos do Chrome.</p></div><div><button onClick={refresh}>↻ ATUALIZAR</button><button className="primary" onClick={createJobs}>▶ CRIAR JOBS DOS PROMPTS</button></div></div><div className="agentContract"><span>CORE</span><b>GET jobs PENDING</b><i>→</i><span>CORVO AGENT</span><b>executa Flow</b><i>→</i><span>CORE</span><b>PATCH job DONE</b></div>{!project.jobs.length?<Empty title="Fila vazia" text="Crie prompts nas cenas e gere os jobs. O Flow Agent será conectado a esta fila no próximo passo."/>:<div className="jobs">{project.jobs.map(j=><article key={j.id}><span className={`jobStatus ${j.status.toLowerCase()}`}>{j.status}</span><div><b>{j.outputFile||j.id}</b><small>{j.type} · tentativa {j.attempt}</small><p>{j.prompt}</p>{j.error&&<em>{j.error}</em>}</div><time>{new Date(j.updatedAt).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</time></article>)}</div>}</section>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><b>◇</b><h3>{title}</h3><p>{text}</p></div>}
function NewProject({close,submit,busy}:{close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><header><div><em>NOVO CORE</em><h2>Criar projeto</h2></div><button type="button" onClick={close}>×</button></header><label className="full">TÍTULO<input name="title" required autoFocus placeholder="Ex.: VOCÊ SOBREVIVERIA NO DESERTO?"/></label><label className="full">TEMA<input name="topic" placeholder="sobrevivência no deserto"/></label><div className="formGrid"><label>FORMATO<select name="format"><option>REELS</option><option>VÍDEO COMPLETO</option></select></label><label>QUANTIDADE<select name="quantity"><option>1 VÍDEO</option><option>LOTE</option></select></label><label>MODO<select name="mode"><option>RÁPIDO</option><option>PESQUISAR ANTES</option></select></label></div><footer><button type="button" onClick={close}>CANCELAR</button><button className="primary" disabled={busy}>{busy?"CRIANDO...":"＋ CRIAR PROJETO"}</button></footer></form></div>}
